### ISSUE TITLE
[BUG] Jake crashes on ddt scan "TypeError: 'int' object is not callable"

### ISSUE THREAD

**Issue by arichtman** [sonatype-nexus-community/jake#100]
**Describe the bug**
When running a Jake scan it crashes out attempting to call an _int_ object somewhere in TinyDB.

**To Reproduce**
1. Clone the repository https://github.com/arichtman/foxOps
2. Enter the virtual environment and run Jake `poetry run jake ddt`
2. See error

**Expected behavior**
Normal execution of Jake OSS Index-backed scan

**Screenshots**
![image](https://user-images.githubusercontent.com/10679234/152668362-e1fa45e9-bced-4cf1-b45c-e971cd16031b.png)

**Desktop (please complete the following information):**
 - OS: WSL2 Ubuntu 20.04 LTS
 - Uname -a: `Linux bruce-banner 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Python Version: 3.10.1
 - Version 1.4.3

**Additional context**
os-release:
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by madpah** [comment]
Hi @arichtman - thanks for the bug ticket.

This is a known issue with a downstream dependency https://github.com/sonatype-nexus-community/ossindex-python/issues/2.

Whilst we get that resolved in the downstream dependency, you can add the flag `--clear-cache` to you `jake` command which will circumvent the caching of responses from OSS Index.

**Comment by arichtman** [comment]
Many thanks for your response. Have a great day!
