### ISSUE TITLE
[FEATURE] Support for all input formats when running `jake ddt` or `jake iq`

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/jake#104]
`jake` is built upon [`cyclonedx-python`](https://github.com/CycloneDX/cyclonedx-python) which supports consuming dependencies in multiple forms:

- Current Python Environment (`jake ddt` already supports this)
- requirements.txt
- Pipfile.lock
- poetry.lock
- Output from `conda list`
- Output from `conda list --json`

This feature will delivery the ability to consume dependencies from all of the above formats when running either `jake ddt` or `jake iq`.

cc @bhamail / @DarthHater

**Comment by sanzoghenzo** [comment]
Hi, forgive me if I'm being _that_ guy, but... are there any update on this? :wink: 

I took a very quick look at the source code, it seems that it's a matter of changing the [parser initialization](https://github.com/sonatype-nexus-community/jake/blob/9f0bd5230ce989463af3ad75750ce8fa1708843d/jake/command/oss.py#L81) using the same code as the [`SbomCommand._get_parser` medhod](https://github.com/sonatype-nexus-community/jake/blob/9f0bd5230ce989463af3ad75750ce8fa1708843d/jake/command/sbom.py#L146) - or even better turn that method into a function that accepts input type and input source, so it can be simplified and reused.

Obviously the [two arguments](https://github.com/sonatype-nexus-community/jake/blob/9f0bd5230ce989463af3ad75750ce8fa1708843d/jake/command/sbom.py#L114-L132) needs to be ported to the other commands.

Am I missing something?
