### ISSUE TITLE
Alpo Time - use jake to scan jake during CI

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/jake#19]
* **What are you trying to do?**
Update the CI config of the jake project to run jake against itself and report any vulnerabilities found. CI should fail if vulnerabilities are found.

* **What feature or behavior is this required for?**
Yummy dog food.

* **How could we solve this issue? (Not knowing is okay!)**
Update CI with yummy goodness

* **Anything else?**
Dunno

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
So you'll wanna use https://ossindex.sonatype.org/integration/ossaudit for this, not `jake`! Jake just Conda, but it should get scanned, for sure!

**Comment by ButterB0wl** [comment]
well we can use jake on jake now!

**Comment by bhamail** [comment]
Fixed in 7526728623e102fb75fad30eb82be8824abbdf39
