### ISSUE TITLE
[BUG] Pinned to Yaml 5.3.1, which is insecure

### ISSUE THREAD

**Issue by matthewdeanmartin** [sonatype-nexus-community/jake#51]
Jake pins the versions, so when the host apps installs the updated secure library, jake comes in and uninstalls the secure library and installs an insecure library.

> - PyYAML [required: ==5.3.1, installed: 5.3.1]

Ref to vulnerability bulletin: https://snyk.io/vuln/pip:pyyaml

Please stop pinning versions, or if you really like pinning versions you need to update your pinned versions the day that `safety` publishes vulnerabilities and get your version out to pypi.

**Comment by jwa5426** [comment]
It looks like this was fixed. In the PR I have opened (https://github.com/sonatype-nexus-community/jake/pull/59) `safety` doesn't flag anything. It would probably be a good idea to add a CI step that runs `safety` though.

**Comment by bhamail** [comment]
I think this is fixed by #59, so please holler if it is still an issue.
