### ISSUE TITLE
-r problems

### ISSUE THREAD

**Issue by ltratcliff** [sonatype-nexus-community/jake#63]
Trying to point to a requirements file and having issues. Am I missing something dumb? Thanks <3

![image](https://user-images.githubusercontent.com/9104793/129626927-860bb200-a527-4a28-9c92-97a70cfdb343.png)

**Comment by ltratcliff** [comment]
I'm a dope, belay my last... name, version = ... derp :dog: 

requirements of requests==1.2 did the trick.

Sorry! (and thanks!)

**Comment by bhamail** [comment]
@ltratcliff No apologies needed. And I'm pretty sure I can out dumb you!

Seriously, Thanks for taking the time to post an issue. It may help others later. Glad you got it working.
