### ISSUE TITLE
[BUG] Jake may exit with exit code 0 given a high number of vulnerabilities

### ISSUE THREAD

**Issue by itamarst** [sonatype-nexus-community/jake#65]
Jake exits with an exit code which is the number of vulnerabilities. The problem is that exit codes have a limit, and when that limit is exceeded unexpected things happen.

```shell-session
$ python -c "import sys; sys.exit(12)" || echo $?
12
$ python -c "import sys; sys.exit(100)" || echo $?
100
$ python -c "import sys; sys.exit(200)" || echo $?
200
$ python -c "import sys; sys.exit(300)" || echo $?
44
$ python -c "import sys; sys.exit(255)" || echo $?
255
$ python -c "import sys; sys.exit(256)" || echo $?
$ python -c "import sys; sys.exit(256)" && echo $?
0
```

If someone is unlucky enough to have a number of vulnerabilities that is a multiple of 256, the exit code will be zero, indicating everything is fine... 

You probably want to do something like `code = min(audit.audit_results(), 255)` instead of just using the result of `audit_results()` as is.

**Comment by DarthHater** [comment]
This seems silly. We should just exit with `1`. I think there was a pattern wayyyy back in the day to exit with the vuln count, but as you point out, it is not exactly predictable doing so. Would gladly accept a PR for switching it to just exit with `1` when it finds bad things, and `0` otherwise

**Comment by madpah** [comment]
Since `jake` `>=1.0.0`, we don't actually have the above reported behaviour. However, we also don't exit with`1` if there are issues found.

Will get on an update for this.

**Comment by madpah** [comment]
`jake v1.0.1` has updated handling for this now.
