### ISSUE TITLE
[REVIEW] Review all dependencies

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/jake#73]
Given the point raised in #72, we need to assess all dependencies used in `jake` and confirm if they are required, maintained, supported etc..

This may lead to vendorising some packages that are no longer maintained and/or removing them from `jake` if their value is not important enough.

**Comment by madpah** [comment]
Currently declared dependencies:

| Dependency | Version Range | Available as Binary / Wheel |
| ------------- | ------------- | ------------- | 
click | ^8.0.1 | Y
colorama | ^0.4.4 | Y
cyclonedx-python-lib | ^0.10.2 | Y
ossindex-lib | ^0.2.1 | Y
polling2 | ^0.5.0 | Y
pyfiglet | ^0.8.post1 | Y
PyYAML | ^5.4.1 | Y - see #71
requests | ^2.26.0 | Y
termcolor-whl | ^1.1.2 | Y - see #72 
terminaltables | ^3.1.7 | Y - see #72 
tinydb | ^4.5.1 | Y
yaspin | ^2.1.0 | Y, but transitive of `termcolor` is not - see #72

Aim of this issue is to:
1. Ensure all dependencies are available as binaries
2. Review dependencies for inactivity etc. and substitute as necessary
3. Look to loosen dependency constraints to make `jake` more consumable in existing environments - see #71

**Comment by matthewdeanmartin** [comment]
You can straight up remove termcolor-whl, I thought y'all had a direct dependency on termcolor, so my bad suggestion.

**Comment by madpah** [comment]
**NOTE:** It has been discovered that a transitive of `cyclonedx-python-lib` `requirements-parser` is not available as a WHL for Python 3 (only for Python 2).

**Comment by madpah** [comment]
This was removed in `cyclonedx-python-lib` `0.12.3`.

**Comment by madpah** [comment]
It would appear that after #80 is merged, we should now be able to release `jake` so that it can be installed with only binary wheel dependencies @matthewdeanmartin.

**Comment by madpah** [comment]
`jake` `v.1.2.1` released :D

**Comment by matthewdeanmartin** [comment]
I can verify:

```
jake
$ caniuseonlywheels -r requirements.txt
Finding and checking dependencies ...

You (potentially) have 0 projects blocking you from using wheels!
```

**Comment by madpah** [comment]
Excellent - thanks @matthewdeanmartin
