### ISSUE TITLE
[BUG] Strict option placement for -w flag

### ISSUE THREAD

**Issue by arichtman** [sonatype-nexus-community/jake#99]
Hi all, not sure if this is even a bug but I encountered this when trying to set up pre-commit scans that were warn-only. When running Jake scans, the warn option is strictly positional.

1. Run `jake ddt -w`
2. See error _jake: error: unrecognized arguments: -w_

**Expected behavior**
`jake -h ddt` is identical to `jake ddt -x`
According to this `jake -w ddt` should be same as `jake ddt -w`

**Screenshots**
![image](https://user-images.githubusercontent.com/10679234/152668214-f952072f-4b64-4e57-96e6-119cdd419728.png)

**Desktop (please complete the following information):**
 - OS: WSL/Ubuntu 20.04 LTS 
 - Uname -a: `Linux bruce-banner 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Python Version: Python 3.10.1
 - Version jake 1.4.3

**Additional context**
os-release:
```bash
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by madpah** [comment]
Hi @arichtman - again, thanks for taking the time to raise this issue.

So I'm clear, the flags `-h`, `-v`, `-w` and `-X` are designed to be global and come before the command (e.g. `ddt`).

Are you suggesting this should not be the case?

**Comment by arichtman** [comment]
Ah ok, then perhaps the `-w` would make sense after, as it does not apply to `sbom` subcommand?
